<?xml version="1.0"?>
<robot name="seven_dof_arm" xmlns:xacro="http://www.ros.org/wiki/xacro">


  <xacro:include filename="$(find seven_dof_robot_description)/urdf/materials.xacro"/>
  <xacro:include filename="$(find seven_dof_robot_description)/urdf/seven_dof_arm.gazebo"/>

  <!-- PROPERTY LIST -->

  <!-- Constans -->
  <xacro:property name="deg_to_rad" value="0.01745329251994329577"/>
  <xacro:property name="M_SCALE" value="0.001 0.001 0.001"/>
  <xacro:property name="M_PI" value="3.14159"/>

  <!-- Shoulder pan link properties -->
  <xacro:property name="shoulder_pan_width" value="0.04"/>
  <xacro:property name="shoulder_pan_len" value="0.08"/>

  <!-- Sholder pitch link properties -->
  <xacro:property name="shoulder_pitch_len" value="0.14"/>
  <xacro:property name="shoulder_pitch_width" value="0.04"/>
  <xacro:property name="shoulder_pitch_height" value="0.04"/>

  <!-- Elbow roll link properties -->
  <xacro:property name="elbow_roll_width" value="0.02"/>
  <xacro:property name="elbow_roll_len" value="0.06"/>

  <!-- Elbow pitch link properties -->
  <xacro:property name="elbow_pitch_len" value="0.22"/>
  <xacro:property name="elbow_pitch_width" value="0.04"/>
  <xacro:property name="elbow_pitch_height" value="0.04"/>

  <!-- Wrist roll link properties -->
  <xacro:property name="wrist_roll_width" value="0.02"/>
  <xacro:property name="wrist_roll_len" value="0.04"/>

  <!-- Wrist pitch link properties -->
  <xacro:property name="wrist_pitch_len" value="0.06"/>
  <xacro:property name="wrist_pitch_width" value="0.04"/>
  <xacro:property name="wrist_pitch_height" value="0.04"/>

  <!-- Gripper roll link properties -->
  <xacro:property name="gripper_roll_width" value="0.04"/>
  <xacro:property name="gripper_roll_len" value="0.02"/>

  <!-- Left gripper -->
  <xacro:property name="left_gripper_len" value="0.08"/>
  <xacro:property name="left_gripper_width" value="0.01"/>
  <xacro:property name="left_gripper_height" value="0.01"/>

  <!-- Right gripper -->
  <xacro:property name="right_gripper_len" value="0.08"/>
  <xacro:property name="right_gripper_width" value="0.01"/>
  <xacro:property name="right_gripper_height" value="0.01"/>

  <!-- Grasp gripper -->
  <xacro:property name="grasp_frame_len" value="0.02"/>
  <xacro:property name="grasp_frame_width" value="0.02"/>
  <xacro:property name="grasp_frame_height" value="0.02"/>

  <!-- XACRO:MACRO -->

  <!-- xacro:macro for inertia matrix -->
  <xacro:macro name="inertia_matrix" params="mass">
    <inertial>
      <mass value="${mass}"/>
    <inertia  ixx="1.0" ixy="0.0" ixz="0.0" 
              iyy="0.5" iyz="0.0" 
              izz="1.0"/>
    </inertial>
  </xacro:macro>

  <!-- xacro:macro for transmission block -->
  <xacro:macro name="transmission_block" params="trans_name joint_name motor_name">
    <transmision name="${trans_name}">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${joint_name}">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
      <actuator name="${motor_name}">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmision>
  </xacro:macro>

    <!-- LINKS AND JOINTS -->

  <!-- WORLD_LINK -->
  <link name="world"/>

  <!-- FIXED_JOINT-->
  <joint name="fixed_joint" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
    <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
  </joint>

  <!-- BOTTOM_LINK -->
  <!-- <link name="bottom_link">
    
    <visual>
      <origin xyz="0.0 0.0 0.01" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="1 1 0.02"/>
      </geometry>
      <material name="White"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="1 1 0.02"/>
      </geometry>
    </collision>
    
    <xacro:inertia_matrix mass="1000"/>
  
  </link> -->

  <!-- BOTTOM_BASE _JOINT -->
  <!-- <joint name="bottom_base_joint" type="fixed">
    <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    <parent link="bottom_link"/>
    <child link="base_link"/>
  </joint> -->

  <!-- BASE_LINK -->
  <link name="base_link">
    
    <visual>
      <origin xyz="0 0 0.05" rpy="${M_PI/2} 0.0 0.0"/>
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
      <material name="Gray"/>
    </visual>

    <collision>
      <origin xyz="0.0 0.0 0.05" rpy="${M_PI/2} 0.0 0.0"/>
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>

    <xacro:inertia_matrix mass="1"/>

  </link>

  <!-- SHOULDER_PAN_JOINT -->
  <joint name="shoulder_pan_joint" type="revolute">
    <parent link="base_link"/>
    <child link="shoulder_pan_link"/>
    <limit lower="-2.61799387799" upper="1.98394848567" effort="300" velocity="1"/>
    <origin xyz="0.0 0.0 0.1" rpy="0.0 0.0 0.0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="50" friction="1"/>
  </joint>

  <!-- SHOULDER_PAN_LINK -->
  <link name="shoulder_pan_link">
    
    <visual>
      <origin xyz="0.0 0.0 0.02" rpy="0.0 0.0 0.0"/>
      <geometry>
        <cylinder radius="${shoulder_pan_width}" length="${shoulder_pan_len}"/>
      </geometry>
    </visual>

    <collision>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 ${M_PI/2} 0.0"/>
      <geometry>
        <cylinder radius="${shoulder_pan_width}" length="${shoulder_pan_len}"/>
      </geometry>
    </collision>

    <xacro:inertia_matrix mass="1"/>
  
  </link>

  <!-- SHOULDER_PITCH_JOINT -->
  <joint name="shoulder_pitch_joint" type="revolute">
    <parent link="shoulder_pan_link"/>
    <child link="shoulder_pitch_link"/>
    <limit effort="300" velocity="1" lower="-1.19962513147" upper="1.89994105047"/>
    <origin xyz="0.0 0.0 ${shoulder_pan_len/2}" rpy="0.0 0.0 0.0"/>
  </joint>

  <!-- SHOULDER_PITCH_LINK -->
  <link name="shoulder_pitch_link">
    
    <visual>
      <origin xyz="0.0 0.0 ${shoulder_pan_len}" rpy="0.0 ${M_PI/2} 0.0"/>
      <geometry>
        <box size="${shoulder_pitch_len} ${shoulder_pitch_width} ${shoulder_pitch_height}"/>
      </geometry>
      <material name="Gray"/>
    </visual>

    <collision>
      <origin xyz="0.0 0.0 ${shoulder_pan_len}" rpy="0.0 ${M_PI/2} 0.0"/>
      <geometry>
        <box size="${shoulder_pitch_len} ${shoulder_pitch_width} ${shoulder_pitch_height}"/>
      </geometry>
    </collision>

    <xacro:inertia_matrix mass="1"/>
  
  </link>

  <!-- ELBOW_ROLL_JOINT -->
  <joint name="elbow_roll_joint" type="revolute">
    <parent link="shoulder_pitch_link"/>
    <child link="elbow_roll_link"/>
    <limit effort="300" velocity="1" lower="-2.61799387799" upper="0.705631162427" />
    <origin xyz="0.0 0.0 ${shoulder_pitch_len}" rpy="0.0 0.0 0.0"/>
    <axis xyz="0.0 0.0 1.0"/>
    <dynamics damping="50" friction="1"/>
  </joint>

  <!-- ELBOW_ROLL_LINK -->
  <link name="elbow_roll_link">
    
    <visual>
      <origin xyz="0.0 0.0 ${elbow_roll_len/2}" rpy="0.0 0.0 0.0"/>
      <geometry>
        <cylinder radius="${elbow_roll_width}" length="${elbow_roll_len}"/>
      </geometry>
      <material name="Black"/>
    </visual>

    <collision>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <cylinder radius="${elbow_roll_width}" length="${elbow_roll_len}"/>
      </geometry>
    </collision>

    <xacro:inertia_matrix mass="1"/>

  </link>

  <!-- ELBOW_PITCH_JOINT -->
  <joint name="elbow_pitch_joint" type="revolute">
    <parent link="elbow_roll_link"/>
    <child link="elbow_pitch_link"/>
    <limit effort="300" velocity="1" lower="-1.5953400194" upper="1.93281579274" />
    <origin xyz="0.0 0.0 ${elbow_roll_len/2}" rpy="0.0 0.0 0.0"/>
    <dynamics damping="50" friction="1"/>
  </joint>

  <!-- ELBOW_PITCH_LINK -->
  <link name="elbow_pitch_link">
    
    <visual>
      <origin xyz="0.0 0.0 ${elbow_pitch_len/2}" rpy="0.0 ${M_PI/2} 0.0"/>
      <geometry>
        <box size="${elbow_pitch_len} ${elbow_pitch_width} ${elbow_pitch_height}"/>
      </geometry>
    </visual>

    <collision>
      <origin xyz="0.0 0.0 ${elbow_pitch_len/2}" rpy="0.0 ${M_PI/2} 0.0"/>
      <geometry>
        <box size="${elbow_pitch_len} ${elbow_pitch_width} ${elbow_pitch_height}"/>
      </geometry>
      <material name="Red"/>
    </collision>

    <xacro:inertia_matrix mass="1"/>

  </link>

  <!-- WRIST_ROLL_JOINT -->
  <joint name="wrist_roll_joint" type="revolute">
    <parent link="elbow_pitch_link"/>
    <child link="wrist_roll_link"/>
    <limit effort="300" velocity="1" lower="-2.61799387799" upper="2.6128806087" />
    <origin xyz="0.0 0.0 ${elbow_pitch_len}" rpy="0.0 0.0 0.0"/>
    <axis xyz="0.0 0.0 1"/>
    <dynamics damping="50" friction="1"/>
  </joint>

  <!-- WRIST_ROLL_LINK -->
  <link name="wrist_roll_link">
    
    <visual>
      <origin xyz="0.0 0.0 0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <cylinder radius="${wrist_roll_width}" length="${wrist_roll_len}"/>
      </geometry>
      <material name="Black"/>
    </visual>
  
    <collision>
      <origin xyz="0.0 0.0 0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <cylinder radius="${wrist_roll_width}" length="${wrist_roll_len}"/>
      </geometry>
    </collision>

    <xacro:inertia_matrix mass="1"/>
  </link>

  <!-- WRIST_PITCH_JOINT -->
  <joint name="wrist_pitch_joint" type="revolute">
    <parent link="wrist_roll_link"/>
    <child link="wrist_pitch_link"/>
    <origin xyz="0.0 0.0 ${wrist_roll_len/2}" rpy="0.0 0.0 0.0"/>
    <limit effort="300" velocity="1" lower="-1.5953400194" upper="1.98394848567" />
    <dynamics damping="50" friction="1"/>
  </joint>

  <!-- WRIST_PITCH_LINK -->
  <link name="wrist_pitch_link">
    
    <visual>
      <origin xyz="0.0 0.0 ${wrist_pitch_len/2}" rpy="0.0 ${M_PI/2} 0.0"/>
      <geometry>
        <box size="${wrist_pitch_len} ${wrist_pitch_width} ${wrist_pitch_height}"/>
      </geometry>
      <material name="Gray"/>
    </visual>

    <collision>
      <origin xyz="0.0 0.0 ${wrist_pitch_len/2}" rpy="0.0 ${M_PI/2} 0.0"/>
      <geometry>
        <box size="${wrist_pitch_len} ${wrist_pitch_width} ${wrist_pitch_height}"/>
      </geometry>
    </collision>

    <xacro:inertia_matrix mass="1"/>
  
  </link>

  <!-- GRIPPER_ROLL_JOINT -->
  <joint name="gripper_roll_joint" type="revolute">
    <parent link="wrist_pitch_link"/>
    <child link="gripper_roll_link"/>
    <origin xyz="0.0 0.0 ${wrist_pitch_len}" rpy="0.0 0.0 0.0"/>
    <axis xyz="0.0 0.0 1.0"/>
    <limit effort="300" velocity="1" lower="-3.14" upper="3.14" />
    <dynamics damping="50" friction="1"/>
  </joint>

  <!-- GRIPPER_ROLL_LINK -->
  <link name="gripper_roll_link">
    
    <visual>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <cylinder radius="${gripper_roll_width}" length="${gripper_roll_len}"/>
      </geometry>
      <material name="Red"/>
    </visual>

    <collision>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <cylinder radius="${gripper_roll_width}" length="${gripper_roll_len}"/>
      </geometry>
    </collision>

    <xacro:inertia_matrix mass="1"/>

  </link>

  <!-- Finger_joint_1 -->
  <joint name="finger_joint1" type="prismatic">
    <parent link="gripper_roll_link"/>
    <child link="gripper_finger_link1"/>
    <limit effort="100" lower="0" upper="0.03" velocity="1.0"/>
    <origin xyz="0.0 0.0 ${wrist_roll_len/4}" rpy="0.0 0.0 0.0"/>
    <axis xyz="1 0.0 0.0"/>
    <dynamics damping="50" friction="1"/>
  </joint>
  
  <!-- LEFT_GRIPPER_LINK -->
  <link name="gripper_finger_link1">
    
    <visual>
      <origin xyz="${left_gripper_width/2} 0.0 ${left_gripper_len/2}" rpy="0.0 ${M_PI/2} 0.0"/>
      <geometry>
        <box size="${left_gripper_len} ${left_gripper_width} ${left_gripper_height}"/>
      </geometry>
      <material name="Gray"/>
    </visual>
  
    <collision>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="${left_gripper_len} ${left_gripper_width} ${left_gripper_height}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.05"/>
      <inertia  ixx="0.0001" ixy="0.0" ixz="0.0" 
                iyy="0.0001" iyz="0.0" 
                izz="0.0001"/>
    </inertial>
  
  </link>

  <!-- Finger_joint_2 -->
  <joint name="finger_joint2" type="prismatic">
    <parent link="gripper_roll_link"/>
    <child link="gripper_finger_link2"/>
    <limit effort="100" lower="0" upper="0.03" velocity="1.0"/>
    <origin xyz="0.0 0.0 ${wrist_roll_len/4}" rpy="0.0 0.0 0.0"/>
    <axis xyz="-1 0.0 0.0"/>
    <dynamics damping="50" friction="1"/>
  </joint>

    <!-- RIGHT_GRIPPER_LINK -->
  <link name="gripper_finger_link2">
    
    <visual>
      <origin xyz="${-right_gripper_width/2} 0.0 ${right_gripper_len/2}" rpy="0.0 ${M_PI/2} 0.0"/>
      <geometry>
        <box size="${right_gripper_len} ${right_gripper_width} ${right_gripper_height}"/>
      </geometry>
      <material name="Gray"/>
    </visual>
  
    <collision>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="${right_gripper_len} ${right_gripper_width} ${right_gripper_height}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.05"/>
      <inertia  ixx="0.0001" ixy="0.0" ixz="0.0" 
                iyy="0.0001" iyz="0.0" 
                izz="0.0001"/>
    </inertial>

  </link>

  <!-- Grasping frame -->
  <link name="grasping_frame">
    
    <visual>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="0.01 0.01 0.01"/>
      </geometry>
      <material name="White"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.0001"/>
      <cuboid_inertia mass="0.0001" x="0.001" y="0.001" z="0.001"/>
      <inertia  ixx="1.0" ixy="0.0"  ixz="0.0"  iyy="100.0"  iyz="0.0"  izz="1.0" />
    </inertial>

  </link>

  <joint name="grasping_frame_joint" type="fixed">
    <parent link="gripper_roll_link"/>
    <child link="grasping_frame"/>  
    <origin xyz="0.0 0.0 0.08" rpy="0.0 0.0 0.0"/>
  </joint>

  <!-- TRANSMISSIONS -->

  <xacro:transmission_block trans_name="trans1" joint_name="shoulder_pan_joint" motor_name="motor1"/>
  <xacro:transmission_block trans_name="trans2" joint_name="shoulder_pitch_joint" motor_name="motor2"/>
  <xacro:transmission_block trans_name="trans3" joint_name="elbow_roll_joint" motor_name="motor3"/>
  <xacro:transmission_block trans_name="trans4" joint_name="elbow_pitch_joint" motor_name="motor4"/>
  <xacro:transmission_block trans_name="trans5" joint_name="wrist_roll_joint" motor_name="motor5"/>
  <xacro:transmission_block trans_name="trans6" joint_name="wrist_pitch_joint" motor_name="motor6"/>
  <xacro:transmission_block trans_name="trans7" joint_name="gripper_roll_joint" motor_name="motor7"/>
  <xacro:transmission_block trans_name="trans7" joint_name="finger_joint1" motor_name="motor7"/>
  <xacro:transmission_block trans_name="trans7" joint_name="finger_joint2" motor_name="motor7"/>

</robot>